name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run backend tests
      run: |
        cd backend
        python -m unittest discover -s tests -p "test_*.py"
        
    - name: Run frontend tests  
      run: |
        cd frontend
        npm ci
        npm run test
        
    - name: Merge pull request
      if: github.event_name == 'push' && success()
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git merge origin/main
        git push
